### ISSUE TITLE
How do you, handle jerky animations?

### ISSUE THREAD

**Issue by osiloke** [armadillu/ofxAnimatable#1]
I was just curious if you had any experience with making smooth animations. As you know, frame based animations are jerky due to the fact that the framerate is not constant. Do you know how to deal with this?

**Comment by microcosm** [comment]
Use delta time.

``` cpp
yourAnimatableinstance.update(ofGetLastFrameTime());
```

[More info](http://forum.openframeworks.cc/t/openframeworks-timing-issues-using-ofgetlastframetime/7896).

**Comment by armadillu** [comment]
yep that can help but make sure to limit those values; I have seen very large floats come out of ofGetLastFrameTime()
