### ISSUE TITLE
Animations don't work if updated by zero

### ISSUE THREAD

**Issue by microcosm** [armadillu/ofxAnimatable#5]
Updating your animatable instance with exactly zero kills the animation going forward. It gets stuck at the reset value. On the first frame `ofGetLastFrametime()` returns exactly zero. So if you do this:

``` cpp
void update() {
    myAnimatableInstance.update(ofGetLastFrameTime());
}
```

You end up with a dead animation. You can fix it by doing one of these:

``` cpp
void update() {
    if(ofGetLastFrameTime() > 0) {
        myAnimatableInstance.update(ofGetLastFrameTime());
    }
}
//or
void update() {
    if(ofGetFrameNum() > 0) {
        myAnimatableInstance.update(ofGetLastFrameTime());
    }
}
```

Just thought I'd publish this in case anyone else is stuck on that.

**Comment by armadillu** [comment]
In my experience using variable DT leads to non-smooth animations, so I don't recommend using ofGetLastFrametime() for your delta time in update(dt).

But if you do; you should clamp the values indeed. I've seen ofGetLastFrameTime() return really high values too.

**Comment by microcosm** [comment]
What do you recommend to get the smoothest animations?

**Comment by armadillu** [comment]
oh sorry, a fixed DT; 1.0f/60.0f if you are running at 60fps

**Comment by microcosm** [comment]
Interesting. Fixed works OK on my MBP/OSX, but on Ubuntu (running on a
Jetson TK1) it's all over the place. Whereas I get good results using
ofGetLastFrametime() on both OSX and Ubuntu. Just my experience though.

On Sat, Nov 7, 2015 at 5:48 PM, Oriol Ferrer Mesià <notifications@github.com

> wrote:
> 
> oh sorry, a fixed DT; 1.0f/60.0f if you are running at 60fps
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/armadillu/ofxAnimatable/issues/5#issuecomment-154760919
> .

## 

_Andrew McWilliams_

http://jahya.net/

jahya.net
hardwarehacklab.io
artahack.io

**Comment by moebiussurfing** [comment]
What about to use 1.0f/ofGetFramerate() on update?

**Comment by armadillu** [comment]
ofGetFramerate() will return values very close to 60 (or your target framerate) but not quite 60. This will lead to object being animated following that DT to move unevenly (ie the object will advance a slightly different N pixels every frame). If your app is consistently hitting the target framerate, you are much better off using 60 instead of any flavour of variable DT.
