### ISSUE TITLE
"start after wait" not always working

### ISSUE THREAD

**Issue by jvelazqueztraut** [armadillu/ofxAnimatable#7]
I think the issue comes from this code:

```
void ofxAnimatable::update(float dt){

    if (delay_ > 0.0f ){
        delay_ -= dt;
        if (delay_ < 0.0f){
            startAfterWait();
        }
    }
```

It is not considering the "delay_ == 0.0f" case.
I guess the second conditional statement should be "delay_ <= 0.0f"

**Comment by armadillu** [comment]
I never saw this happen, but you are right! These float comparisons are known to not behave the same way on all platforms. I'm fixing it now
